# Generated by Django 5.1.6 on 2025-06-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_isactive_useraccount_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="cpf",
            field=models.CharField(default="00000000000", max_length=14),
        ),
    ]
