
INSERT INTO questionario_modulo (nome, perguntasQntd, descricao, tempo) VALUES
('Diagnóstico Organizacional', 0, 'O presente formulário é destinado a micro e pequenas empresas que pretendem realizar um diagnóstico de sua situação empresarial. Não há respostas certas ou erradas, as perguntas devem ser respondidas com sinceridade para maior precisão do resultado. O formulário está estruturado em 7 dimensões e o tempo previsto de preenchimento é de 5 minutos.', 0);

INSERT INTO questionario_dimensao (titulo, descricao, tipo, modulo_id, explicacao) VALUES
('Estratégia Empresarial', 'Avalie as questões referentes à ESTRATÉGIA EMPRESARIAL da sua empresa, indicando em uma escala de concordância de 1 a 5 onde 1 significa discordo totalmente e 5 significa concordo totalmente.', 'OBRIGATORIO', 1, 'Explicacao'),
('Estrutura Organizacional', 'Avalie as questões referentes à ESTRUTURA ORGANIZACIONAL da sua empresa, indicando em uma escala de concordância de 1 a 5 onde 1 significa discordo totalmente e 5 significa concordo totalmente.', 'OBRIGATORIO', 1, 'Explicacao'),
('Gestão de Marketing', 'Avalie as questões referentes à GESTÃO DE MARKETING da sua empresa, indicando em uma escala de concordância de 1 a 5 onde 1 significa discordo totalmente e 5 significa concordo totalmente.', 'OBRIGATORIO', 1, 'Explicacao'),
('Gestão Financeira', 'Avalie as questões referentes à GESTÃO FINANCEIRA da sua empresa, indicando em uma escala de concordância de 1 a 5 onde 1 significa discordo totalmente e 5 significa concordo totalmente.', 'OBRIGATORIO', 1, 'Explicacao'),
('Gestão de Pessoas', 'Avalie as questões referentes à GESTÃO DE PESSOAS da sua empresa, indicando em uma escala de concordância de 1 a 5 onde 1 significa discordo totalmente e 5 significa concordo totalmente.', 'OBRIGATORIO', 1, 'Explicacao'),
('ESG', 'Avalie as questões referentes às políticas ESG (Ambiental, Social e Governança) da sua empresa, indicando em uma escala de concordância de 1 a 5 onde 1 significa discordo totalmente e 5 significa concordo totalmente.', 'OBRIGATORIO', 1, 'Explicacao'),
('Gestão Comercial', 'Avalie as questões referentes à GESTÃO COMERCIAL da sua empresa, indicando em uma escala de concordância de 1 a 5 onde 1 significa discordo totalmente e 5 significa concordo totalmente.', 'COMERCIO', 1, 'Explicacao'),
('Gestão Industrial', 'Avalie as questões referentes à GESTÃO INDUSTRIAL da sua empresa, indicando em uma escala de concordância de 1 a 5 onde 1 significa discordo totalmente e 5 significa concordo totalmente.', 'INDUSTRIA', 1, 'Explicacao'),
('Prestação de Serviços', 'Avalie as questões referentes à Prestação de Serviços da sua empresa, indicando em uma escala de concordância de 1 a 5 onde 1 significa discordo totalmente e 5 significa concordo totalmente.', 'SERVICO', 1, 'Explicacao');

INSERT INTO questionario_pergunta (pergunta, dimensao_id, peso) VALUES
('A empresa possui objetivos de longo prazo (mais de 1 ano)?', 1, 1),
('A empresa acompanha constantemente as atividades de seus concorrentes?', 1, 1),
('A empresa analisa fatores externos (ex: economia, cultura, hábitos de compra e tecnologia)?', 1, 1),
('A empresa estabelece metas e objetivos de curto prazo (até 1 ano)?', 1, 1),
('A empresa tem bem definida sua missão e visão?', 1, 1),
('As tarefas na empresa são claras e de conhecimento de toda a equipe?', 2, 1),
('Os processos dentro da empresa estão bem definidos?', 2, 1),
('As funções das pessoas e equipes dentro da sua empresa estão bem-organizadas?', 2, 1),
('Sua empresa possui uma clara organização e estruturação interna?', 2, 1),
('As atividades na empresa possuem um bom fluxo de trabalho?', 2, 1),
('A empresa conhece bem quais são as necessidades e desejos dos seus clientes?', 3, 1),
('A empresa possui uma marca forte que representa sua identidade perante o mercado?', 3, 1),
('A proposta de valor da empresa está bem definida e é bem comunicada ao mercado?', 3, 1),
('A empresa possui diferentes meios de comunicação de marketing (online e offline) que são atualizados constantemente?', 3, 1),
('Os produtos e serviços comercializados pela empresa atendem às expectativas do mercado?', 3, 1),
('A empresa separa bem as contas da pessoa jurídica das contas da pessoa física?', 4, 1),
('A empresa utiliza o fluxo de caixa para gestão financeira?', 4, 1),
('A empresa possui controle de contas a pagar e contas a receber?', 4, 1),
('A empresa analisa algum tipo de demonstrativo ou indicador financeiro (ponto de equilíbrio, margem de contribuição, DRE, Balanço Patrimonial ou outros)?', 4, 1),
('A empresa realiza algum tipo de planejamento financeiro?', 4, 1),
('O clima organizacional da empresa é saudável?', 5, 1),
('As pessoas recebem treinamento e orientações para executarem suas funções?', 5, 1),
('Os salários, benefícios e condições de trabalho são equiparáveis ao setor de atuação da empresa?', 5, 1),
('As habilidades técnicas e comportamentais da equipe são monitoras e desenvolvidas individualmente?', 5, 1),
('Os funcionários recebem feedback sobre o trabalho realizado na empresa?', 5, 1),
('A empresa se preocupa constantemente com a redução de desperdícios e busca minimizar o uso de recursos (água, energia, papel etc.)?', 6, 1),
('A empresa promove ações de educação e conscientização ambiental?', 6, 1),
('A empresa se preocupa com a qualidade de vida de seus funcionários?', 6, 1),
('A empresa se preocupa com o ambiente social que está inserida, realizando ações de responsabilidade social?', 6, 1),
('A empresa possui uma gestão idônea, ética e responsável, seguindo as leis e normas do setor que está inserida?', 6, 1),
('A empresa tem um bom controle de estoque?', 7, 1),
('A empresa conhece os períodos de sazonalidade do setor?', 7, 1),
('A empresa possui um bom relacionamento com seus fornecedores?', 7, 1),
('A empresa se preocupa com a boa apresentação dos produtos no seu ponto de venda?', 7, 1),
('Os clientes estão satisfeitos com o atendimento dos vendedores?', 7, 1),
('A empresa tem um bom controle de estoque?', 8, 1),
('A empresa possui um bom relacionamento com seus fornecedores?', 8, 1),
('A empresa realiza planejamento e controle da produção?', 8, 1),
('A empresa conhece os custos fixos e variáveis do seu processo produtivo?', 8, 1),
('A empresa acompanha e controla sua produtividade?', 8, 1),
('A empresa conhece bem as expectativas dos seus clientes?', 9, 1),
('A empresa possui equipe qualificada para prestar serviços com qualidade?', 9, 1),
('A empresa transmite confiança e credibilidade?', 9, 1),
('A empresa cumpre os prazos acordados com os clientes?', 9, 1),
('A empresa possui os recursos e equipamentos necessários para prestar seus serviços com qualidade?', 9, 1);