# Generated by Django 5.1.6 on 2025-06-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionario", "0002_alter_dimensao_modulo_respostamodulo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pergunta",
            name="explicacao",
        ),
        migrations.AddField(
            model_name="dimensao",
            name="explicacao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pergunta",
            name="peso",
            field=models.IntegerField(default=1),
        ),
    ]
