# Generated by Django 5.1.6 on 2025-06-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "questionario",
            "0003_remove_pergunta_explicacao_dimensao_explicacao_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="respostamodulo",
            unique_together=set(),
        ),
    ]
