# Generated by Django 5.1.6 on 2025-06-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionario", "0004_alter_respostamodulo_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="respostadimensao",
            unique_together=set(),
        ),
    ]
