# Generated by Django 5.1.6 on 2025-07-01 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionario", "0005_alter_respostadimensao_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="respostadimensao",
            name="modulo",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="questionario.respostamodulo",
            ),
            preserve_default=False,
        ),
    ]
