# Generated by Django 5.1.6 on 2025-07-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionario", "0006_respostadimensao_modulo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="respostadimensao",
            old_name="modulo",
            new_name="resposta_modulo",
        ),
    ]
