# Generated by Django 5.1.6 on 2025-08-06 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionario", "0007_rename_modulo_respostadimensao_resposta_modulo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RespostaModuloIncompleta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("respostas", models.JSONField(default=dict)),
                ("dataResposta", models.DateTimeField(auto_now=True)),
                (
                    "modulo",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas_incompletas",
                        to="questionario.modulo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Respostas Incompletas dos Módulos",
            },
        ),
    ]
